# Generated by Django 2.2.6 on 2022-04-01 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0007_auto_20220401_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeplan',
            name='day_name',
            field=models.CharField(choices=[('1', 'Poniedziałek'), ('2', 'Wtorek'), ('3', 'Środa'), ('4', 'Czwartek'), ('5', 'Piątek'), ('6', 'Sobota'), ('7', 'Niedziela')], max_length=64),
        ),
        migrations.AlterField(
            model_name='recipeplan',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='jedzonko.Plan'),
        ),
        migrations.AlterField(
            model_name='recipeplan',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='jedzonko.Recipe'),
        ),
    ]
